name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Change this based on your project

      - name: Install dependencies
        run: npm install # Change to yarn or pnpm if needed

      - name: Build project
        run: npm run build # Ensure your build command is correct

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./host-app/dist # Change this to your build output directory
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions 🚀"
          enable-pull-request-comment: false
          enable-commit-comment: false
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_HOST_SITE_ID }}
