[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/assets/remoteEntry.js"
  to = "https://remote-mfa.netlify.app/assets/remoteEntry.js"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"