[[headers]]
  for = "/assets/remoteEntry.js"
  [headers.values]
    Access-Control-Allow-Origin = "https://host-mfa.netlify.app"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
